sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.4.1
before_install:
  - gem update --system
  - bundle config set without 'development'
  - gem install bundler
branches:
  only:
    - release
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
deploy:
  provider: pages
  local-dir: "./_site"
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  on:
    branch: release
